use std::sync::{Arc, Mutex};

use crate::db::models::{validate_agent_name, Reflection};
use rusqlite::{params, Result};
use serde_json::Value;

const CREATE_REFLECTION: &str = "
    INSERT INTO reflections (reflection_id, session_id, content, type, importance, level, source_summary, agent_name, created_at, deleted_at)
    VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
";
const GET_REFLECTION_BY_SESSION: &str = "
    SELECT reflection_id, session_id, content, type, importance, level, source_summary, agent_name, created_at, deleted_at
    FROM reflections
    WHERE session_id = ?1 AND deleted_at IS NULL
";

const DELETE_REFLECTION: &str = "
    UPDATE reflections SET deleted_at = ?1 WHERE reflection_id = ?2
";

#[derive(Debug)]
pub struct ParsedReflection {
    pub content: String,
    pub r#type: String,
    pub importance: f32,
    pub level: String,
    pub source_summary: String,
}

/// Parse reflection content generated by external agent (Tyrion/opencode-go)
/// Expected structure:
/// ```ignore
/// {
///     "content": "...",
///     "type": "pattern|principle|warning",
///     "importance": 0.85,
///     "level": "Fact|Pattern|Principle",
///     "source_summary": "..."
/// }
/// ```
///
/// If content is NOT valid JSON, it will be treated as plain text and wrapped
/// as an "insight" type reflection automatically (for backward compatibility).
fn parse_reflection_content(content: &str) -> Result<ParsedReflection> {
    let trimmed = content.trim();

    // Try to parse as JSON
    let json_result: Result<Value, _> = serde_json::from_str(trimmed);

    match json_result {
        Ok(json) => parse_json_reflection(json),
        Err(_) => {
            // Not valid JSON - treat as plain text insight
            // This allows agents to pass Markdown directly
            Ok(ParsedReflection {
                content: trimmed.to_string(),
                r#type: "warning".to_string(),
                importance: 0.5,
                level: "Fact".to_string(),
                source_summary: "Generated from unstructured text (backward compatibility)"
                    .to_string(),
            })
        }
    }
}

fn parse_json_reflection(json: Value) -> Result<ParsedReflection> {
    let content_text = json
        .get("content")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            rusqlite::Error::ToSqlConversionFailure(Box::new(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Falta campo 'content'",
            )))
        })?
        .to_string();

    let r#type = json
        .get("type")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            rusqlite::Error::ToSqlConversionFailure(Box::new(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Falta campo 'type'",
            )))
        })?
        .to_string();

    match r#type.as_str() {
        "pattern" | "principle" | "warning" => {}
        _ => {
            return Err(rusqlite::Error::ToSqlConversionFailure(Box::new(
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("Tipo inválido: {}", r#type),
                ),
            )));
        }
    }

    let importance = json
        .get("importance")
        .and_then(|v| v.as_f64())
        .ok_or_else(|| {
            rusqlite::Error::ToSqlConversionFailure(Box::new(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Falta campo 'importance'",
            )))
        })? as f32;

    if importance < 0.0 || importance > 1.0 {
        return Err(rusqlite::Error::ToSqlConversionFailure(Box::new(
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("Importance debe estar entre 0 y 1: {}", importance),
            ),
        )));
    }

    let level = json
        .get("level")
        .and_then(|v| v.as_str())
        .ok_or_else(|| {
            rusqlite::Error::ToSqlConversionFailure(Box::new(std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                "Falta campo 'level'",
            )))
        })?
        .to_string();

    match level.as_str() {
        "Fact" | "Pattern" | "Principle" => {}
        _ => {
            return Err(rusqlite::Error::ToSqlConversionFailure(Box::new(
                std::io::Error::new(
                    std::io::ErrorKind::InvalidData,
                    format!("Level inválido: {}", level),
                ),
            )));
        }
    }

    let source_summary = json
        .get("source_summary")
        .and_then(|v| v.as_str())
        .unwrap_or("")
        .to_string();

    Ok(ParsedReflection {
        content: content_text,
        r#type,
        importance,
        level,
        source_summary,
    })
}

fn unix_timestamp() -> i64 {
    std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap()
        .as_secs() as i64
}

/// Store a reflection generated by an external agent (Tyrion/opencode-go)
///
/// This function ONLY saves to DB. The content must be pre-generated by the agent.
///
/// # Arguments
/// * `conn` - Database connection
/// * `session_id` - Session ID
/// * `content` - JSON string with the reflection content (must have: content, type, importance, level)
/// * `agent_name` - Name of the agent that generated the reflection
///
/// # Returns
/// The stored Reflection struct
pub fn store_reflection(
    conn: &Arc<Mutex<rusqlite::Connection>>,
    session_id: &str,
    content: &str,
    agent_name: &str,
) -> Result<Reflection> {
    // Validate agent_name
    let agent = validate_agent_name(agent_name).map_err(|e| {
        rusqlite::Error::ToSqlConversionFailure(Box::new(std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            e,
        )))
    })?;

    // Parse the content JSON
    let parsed = parse_reflection_content(content)?;

    // Generate ID and timestamp
    let reflection_id = uuid::Uuid::new_v4().to_string();
    let now = unix_timestamp();

    // Insert into DB
    let conn = conn.lock().unwrap();
    conn.execute(
        CREATE_REFLECTION,
        params![
            reflection_id,
            session_id,
            parsed.content,
            parsed.r#type,
            parsed.importance * 100.0, // Convert 0-1 to 0-100 for storage
            parsed.level,
            parsed.source_summary,
            agent,
            now,
            Option::<i64>::None,
        ],
    )?;

    Ok(Reflection {
        reflection_id,
        session_id: session_id.to_string(),
        content: parsed.content,
        r#type: parsed.r#type,
        importance: parsed.importance * 100.0,
        level: parsed.level,
        source_summary: Some(parsed.source_summary),
        agent_name: agent,
        created_at: now,
    })
}

pub fn get_reflection_by_session(
    conn: &Arc<Mutex<rusqlite::Connection>>,
    session_id: &str,
) -> Result<Option<Reflection>> {
    let conn = conn.lock().unwrap();
    let mut stmt = conn.prepare(GET_REFLECTION_BY_SESSION)?;
    let mut rows = stmt.query(params![session_id])?;

    if let Some(row) = rows.next()? {
        Ok(Some(Reflection {
            reflection_id: row.get(0)?,
            session_id: row.get(1)?,
            content: row.get(2)?,
            r#type: row.get(3)?,
            importance: row.get(4)?,
            level: row.get(5)?,
            source_summary: row.get(6)?,
            agent_name: row.get(7)?,
            created_at: row.get(8)?,
        }))
    } else {
        Ok(None)
    }
}

pub fn delete_reflection(
    conn: &Arc<Mutex<rusqlite::Connection>>,
    reflection_id: &str,
) -> Result<bool> {
    let conn = conn.lock().unwrap();
    let now = unix_timestamp();
    let affected = conn.execute(DELETE_REFLECTION, params![now, reflection_id])?;
    Ok(affected > 0)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_reflection_content_valid() {
        let content = r#"{
            "content": "Test pattern",
            "type": "pattern",
            "importance": 0.85,
            "level": "Pattern",
            "source_summary": "Test summary"
        }"#;

        let parsed = parse_reflection_content(content).unwrap();
        assert_eq!(parsed.content, "Test pattern");
        assert_eq!(parsed.r#type, "pattern");
        assert!((parsed.importance - 0.85).abs() < 0.001);
        assert_eq!(parsed.level, "Pattern");
        assert_eq!(parsed.source_summary, "Test summary");
    }

    #[test]
    fn test_parse_reflection_content_minimal() {
        let content = r#"{
            "content": "Test",
            "type": "principle",
            "importance": 0.5,
            "level": "Fact"
        }"#;

        let parsed = parse_reflection_content(content).unwrap();
        assert_eq!(parsed.source_summary, "");
    }
}
